apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
      - Namespace
      - ResourceQuota
      - StorageClass
      - CustomResourceDefinition
      - MutatingWebhookConfiguration
      - ServiceAccount
      - PodSecurityPolicy
      - NetworkPolicy
      - Role
      - ClusterRole
      - RoleBinding
      - ClusterRoleBinding
      - ConfigMap
      - Secret
      - Endpoints
      - Service
      - LimitRange
      - PriorityClass
      - PersistentVolume
      - PersistentVolumeClaim
      - Deployment
      - StatefulSet
      - CronJob
      - PodDisruptionBudget
    orderLast:
      - ValidatingWebhookConfiguration

resources:
  # Cert-Manager (required for certificate management)
  - ../common/cert-manager/cert-manager/base
  - ../common/cert-manager/kubeflow-issuer/base
  # Istio (required service mesh)
  - ../common/istio-1-22/istio-crds/base
  - ../common/istio-1-22/istio-namespace/base
  - ../common/istio-1-22/istio-install/overlays/oauth2-proxy
  # oauth2-proxy (authentication)
  - ../common/oidc-client/oauth2-proxy/overlays/m2m-self-signed
  # Dex (authentication)
  - ../common/dex/overlays/oauth2-proxy
  # Kubeflow namespace (required)
  - ../common/kubeflow-namespace/base
  # NetworkPolicies (required network policies)
  - ../common/networkpolicies/base
  # Kubeflow Roles (required permissions)
  - ../common/kubeflow-roles/base
  # Kubeflow Istio Resources (required Istio resources)
  - ../common/istio-1-22/kubeflow-istio-resources/base
  # Cluster local gateway (required)
  - ../common/istio-1-22/cluster-local-gateway/base

  # Core applications
  # Kubeflow Pipelines (workflow management)
  - ../apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
  # Central Dashboard (main dashboard)
  - ../apps/centraldashboard/upstream/overlays/oauth2-proxy
  # Admission Webhook (required)
  - ../apps/admission-webhook/upstream/overlays/cert-manager
  # Profiles + KFAM (user profile management)
  - ../apps/profiles/upstream/overlays/kubeflow

  # Jupyter related (core components)
  # Jupyter Web App
  - ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
  # Notebook Controller
  - ../apps/jupyter/notebook-controller/upstream/overlays/kubeflow

  # PVC Viewer (needed for volume management)
  - ../apps/pvcviewer-controller/upstream/base
  # Volumes Web App (volume management)
  - ../apps/volumes-web-app/upstream/overlays/istio

  # User namespace (required)
  - ../common/user-namespace/base
